# Generated by Django 3.2 on 2022-04-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesachievement',
            name='business_sector',
            field=models.CharField(choices=[('SD', 'SD事業部'), ('SD1', 'SD1部'), ('SD2', 'SD2部'), ('SD3', 'SD3部'), ('SD4', 'SD4部'), ('IS', 'IS事業部'), ('IS1', 'IS1部'), ('IS2', 'IS2部'), ('IS3', 'IS3部'), ('PA', 'PA事業部'), ('PA1', 'PA1部'), ('PA2', 'PA2部'), ('LCM', 'LCM事業部'), ('R&D', 'R&D事業部'), ('ZZ', '事業統括本部')], max_length=10, verbose_name='事業部'),
        ),
        migrations.AlterField(
            model_name='salesachievement',
            name='kinds',
            field=models.CharField(choices=[('その他', 'その他'), ('外注', '外注')], max_length=10, verbose_name='種別'),
        ),
        migrations.AlterField(
            model_name='salesachievement',
            name='sales_department',
            field=models.CharField(choices=[('第一営業部', '第一営業部'), ('第二営業部', '第二営業部'), ('BS営業部', 'BS営業部'), ('SI営業部', 'SI営業部')], max_length=10, verbose_name='営業部門'),
        ),
        migrations.AlterField(
            model_name='salesachievement',
            name='supervising_department',
            field=models.CharField(choices=[('SD', 'SD事業部'), ('IS', 'IS事業部'), ('PA', 'PA事業部'), ('LCM', 'LCM事業部'), ('R&D', 'R&D事業部'), ('ZZ', '事業統括本部')], max_length=10, verbose_name='主管部門'),
        ),
        migrations.AlterField(
            model_name='salesachievement',
            name='type_of_contract',
            field=models.CharField(choices=[('委任', '委任'), ('派遣', '派遣'), ('請負', '請負')], max_length=10, verbose_name='契約形態'),
        ),
        migrations.AlterField(
            model_name='salesbudget',
            name='supervising_department',
            field=models.CharField(choices=[('SD', 'SD事業部'), ('SD1', 'SD1部'), ('SD2', 'SD2部'), ('SD3', 'SD3部'), ('SD4', 'SD4部'), ('IS', 'IS事業部'), ('IS1', 'IS1部'), ('IS2', 'IS2部'), ('IS3', 'IS3部'), ('PA', 'PA事業部'), ('PA1', 'PA1部'), ('PA2', 'PA2部'), ('LCM', 'LCM事業部'), ('R&D', 'R&D事業部'), ('ZZ', '事業統括本部')], max_length=10, verbose_name='主管部門'),
        ),
    ]
